apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-user-service
  namespace: spa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spa-user-service
  template:
    metadata:
      labels:
        app: spa-user-service
    spec:
      containers:
        - name: app
          image: docker.io/library/spa-user-service:dev
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 30
