apiVersion: v1
kind: Service
metadata:
  name: spa-user-service
  namespace: spa
spec:
  selector:
    app: spa-user-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  type: ClusterIP
