apiVersion: v1
kind: Service
metadata:
  name: {{ include "spa.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "spa.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
